/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      "colors": {
        "on-secondary": "#263143",
        "inverse-surface": "#d4e4fa",
        "on-secondary-fixed": "#111c2d",
        "on-tertiary-fixed-variant": "#004c69",
        "outline-variant": "#3c4a46",
        "on-tertiary-fixed": "#001e2c",
        "surface-variant": "#273647",
        "secondary-container": "#3e495d",
        "surface-container-lowest": "#010f1f",
        "on-primary-fixed-variant": "#005047",
        "on-error-container": "#ffdad6",
        "surface-tint": "#3cddc7",
        "on-secondary-fixed-variant": "#3c475a",
        "secondary-fixed": "#d8e3fb",
        "error-container": "#93000a",
        "tertiary-container": "#5ec9ff",
        "tertiary": "#afe0ff",
        "on-surface": "#d4e4fa",
        "surface-container-high": "#1c2b3c",
        "tertiary-fixed": "#c4e7ff",
        "outline": "#859490",
        "on-tertiary": "#00354a",
        "on-secondary-container": "#aeb9d0",
        "surface-container-low": "#0d1c2d",
        "surface-bright": "#2c3a4c",
        "inverse-on-surface": "#233143",
        "tertiary-fixed-dim": "#7bd0ff",
        "inverse-primary": "#006b5f",
        "surface-dim": "#051424",
        "on-tertiary-container": "#005371",
        "primary-fixed-dim": "#3cddc7",
        "on-background": "#d4e4fa",
        "background": "#051424",
        "primary-fixed": "#62fae3",
        "on-primary": "#003731",
        "secondary-fixed-dim": "#bcc7de",
        "error": "#ffb4ab",
        "surface-container": "#122131",
        "secondary": "#bcc7de",
        "surface": "#051424",
        "primary-container": "#2dd4bf",
        "on-primary-container": "#00574d",
        "surface-container-highest": "#273647",
        "on-primary-fixed": "#00201c",
        "primary": "#57f1db",
        "on-surface-variant": "#bacac5",
        "on-error": "#690005"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "lg": "24px",
        "xl": "32px",
        "md": "16px",
        "sm": "8px",
        "container-margin": "40px",
        "gutter": "20px",
        "xs": "4px",
        "unit": "4px"
      },
      "fontFamily": {
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"]
      },
      "fontSize": {
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
